services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/www/certbot:/var/www/certbot
  #   networks:
  #     - app_network
  
networks:
  app_network:
    driver: bridge